/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * FakeRESTApi.Web V1
 * OpenAPI spec version: v1
 */

export * from './author';
export * from './book';
export * from './getAuthorsResponse';