/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * FakeRESTApi.Web V1
 * OpenAPI spec version: v1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  Book
} from './types'




  export const getApiV1Books = <TData = AxiosResponse<Book[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/Books`,options
    );
  }
export const postApiV1Books = <TData = AxiosResponse<void>>(
    book: Book, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/Books`,
      book,options
    );
  }
export const getApiV1BooksId = <TData = AxiosResponse<Book>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/Books/${id}`,options
    );
  }
export const putApiV1BooksId = <TData = AxiosResponse<void>>(
    id: number,
    book: Book, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/Books/${id}`,
      book,options
    );
  }
export const deleteApiV1BooksId = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/Books/${id}`,options
    );
  }
export type GetApiV1BooksResult = AxiosResponse<Book[]>
export type PostApiV1BooksResult = AxiosResponse<void>
export type GetApiV1BooksIdResult = AxiosResponse<Book>
export type PutApiV1BooksIdResult = AxiosResponse<void>
export type DeleteApiV1BooksIdResult = AxiosResponse<void>
