/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * FakeRESTApi.Web V1
 * OpenAPI spec version: v1
 */

export interface Author {
  /** @nullable */
  firstName?: string | null;
  id?: number;
  idBook?: number;
  /** @nullable */
  lastName?: string | null;
}
