/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * FakeRESTApi.Web V1
 * OpenAPI spec version: v1
 */
import {
  z as zod
} from 'zod'


export const getApiV1AuthorsResponseItem = zod.object({
  "id": zod.number().optional(),
  "idBook": zod.number().optional(),
  "firstName": zod.string().nullish(),
  "lastName": zod.string().nullish()
})
export const getApiV1AuthorsResponse = zod.array(getApiV1AuthorsResponseItem)

export const postApiV1AuthorsBody = zod.object({
  "id": zod.number().optional(),
  "idBook": zod.number().optional(),
  "firstName": zod.string().nullish(),
  "lastName": zod.string().nullish()
})

export const postApiV1AuthorsResponse = zod.object({
  "id": zod.number().optional(),
  "idBook": zod.number().optional(),
  "firstName": zod.string().nullish(),
  "lastName": zod.string().nullish()
})

export const getApiV1AuthorsAuthorsBooksIdBookParams = zod.object({
  "idBook": zod.number()
})

export const getApiV1AuthorsAuthorsBooksIdBookResponseItem = zod.object({
  "id": zod.number().optional(),
  "idBook": zod.number().optional(),
  "firstName": zod.string().nullish(),
  "lastName": zod.string().nullish()
})
export const getApiV1AuthorsAuthorsBooksIdBookResponse = zod.array(getApiV1AuthorsAuthorsBooksIdBookResponseItem)

export const getApiV1AuthorsIdParams = zod.object({
  "id": zod.number()
})

export const getApiV1AuthorsIdResponse = zod.object({
  "id": zod.number().optional(),
  "idBook": zod.number().optional(),
  "firstName": zod.string().nullish(),
  "lastName": zod.string().nullish()
})

export const putApiV1AuthorsIdParams = zod.object({
  "id": zod.number()
})

export const putApiV1AuthorsIdBody = zod.object({
  "id": zod.number().optional(),
  "idBook": zod.number().optional(),
  "firstName": zod.string().nullish(),
  "lastName": zod.string().nullish()
})

export const putApiV1AuthorsIdResponse = zod.object({
  "id": zod.number().optional(),
  "idBook": zod.number().optional(),
  "firstName": zod.string().nullish(),
  "lastName": zod.string().nullish()
})

export const deleteApiV1AuthorsIdParams = zod.object({
  "id": zod.number()
})

