/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * FakeRESTApi.Web V1
 * OpenAPI spec version: v1
 */
import {
  z as zod
} from 'zod'


export const getApiV1BooksResponseItem = zod.object({
  "id": zod.number().optional(),
  "title": zod.string().nullish(),
  "description": zod.string().nullish(),
  "pageCount": zod.number().optional(),
  "excerpt": zod.string().nullish(),
  "publishDate": zod.string().datetime().optional()
})
export const getApiV1BooksResponse = zod.array(getApiV1BooksResponseItem)

export const postApiV1BooksBody = zod.object({
  "id": zod.number().optional(),
  "title": zod.string().nullish(),
  "description": zod.string().nullish(),
  "pageCount": zod.number().optional(),
  "excerpt": zod.string().nullish(),
  "publishDate": zod.string().datetime().optional()
})

export const getApiV1BooksIdParams = zod.object({
  "id": zod.number()
})

export const getApiV1BooksIdResponse = zod.object({
  "id": zod.number().optional(),
  "title": zod.string().nullish(),
  "description": zod.string().nullish(),
  "pageCount": zod.number().optional(),
  "excerpt": zod.string().nullish(),
  "publishDate": zod.string().datetime().optional()
})

export const putApiV1BooksIdParams = zod.object({
  "id": zod.number()
})

export const putApiV1BooksIdBody = zod.object({
  "id": zod.number().optional(),
  "title": zod.string().nullish(),
  "description": zod.string().nullish(),
  "pageCount": zod.number().optional(),
  "excerpt": zod.string().nullish(),
  "publishDate": zod.string().datetime().optional()
})

export const deleteApiV1BooksIdParams = zod.object({
  "id": zod.number()
})

